# TODO: if zizmor doesn't pass, don't run any other action
name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    branches: ["**"]

concurrency:
  group: gh-actions-security-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: false

      - name: Run zizmor 🌈
        run: |
          uv venv .venv
          uv pip install --require-hashes -r .github/zizmor-requirements.txt
          .venv/bin/zizmor --format=github .github/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
